# Generated by Django 3.1.5 on 2021-01-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('make_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
        ),
        migrations.AddField(
            model_name='make',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicletype'),
        ),
    ]
