# Generated by Django 3.1.5 on 2021-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
